version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      DATABASE_URL: postgresql://todo_user:todo_password@db:5432/todo_db

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
